// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://2wser5nj7rb6loafj6x34mmgzi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7lofavq7nragbn2sbaxsrlz6xu",
    "aws_cognito_identity_pool_id": "us-east-1:d78c3e19-de13-42ab-8578-5d1f7100f8d9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IP2aUnKOK",
    "aws_user_pools_web_client_id": "3k6q9n5195qs6m9l0dcrh00q68"
};


export default awsmobile;
